questions_options = {
    "q1": {"question": "How many variables of interest?", "options": ["One", "Two", "More than Two"]},
    "q2": {"question": "Enter the number of groups/samples in the data?", "options": ["One Sample Problem", "Two Sample Problem", "Multiple Sample Problem"]},
    "q3": {"question": "Enter the number of groups/samples in the data?", "options": ["One Sample Problem", "Two Sample Problem", "Multiple Sample Problem"]},
    "q5": {"question": "Inference concerning mean or variance?", "options": ["mean", "variance"]},
    "q6": {"question": "2 x 2 Contingency Table?", "options": ["Yes", "No"]},
    "q7": {"question": "2 x k Contingency Table?", "options": ["Yes", "No"]},
    "q8": {"question": "RxC Contingency table, R>2 and C>2?", "options": ["Yes", "No"]},
    "q10": {"question": "Are both Variables normal?", "options": ["Yes", "No"]},
    "q11": {"question": "Are you assuming curve comes from a Weibull distribution:", "options": ["Yes", "No"]},
    "q12": {"question": "Are you interested in comparison of survival curves of two groups with limited control of covariates:", "options": ["yes", "no"]},
   
    "q14": {"question": "Do incidence rates remain constant over time:", "options": ["yes", "no"]},
    "q15": {"question": "How many number of ways can the categorical variable be classified into?", "options": ["1", "2", ">2"]},
    "q20": {"question": "Is the data Categorical?", "options": ["Yes", "No"]},
    "q21": {"question": "Is this a one-sample problem -", "options": ["Yes", "No"]},
    "q22": {"question": "RxC Contingency table, R>2 and C>2?", "options": ["Yes", "No"]},
    "q23": {"question": "Samples are independent or not:", "options": ["Independent", "Not Independent"]},
    "q24": {"question": "Inference concerning mean or variance", "options": ["mean", "variance"]},
    "q25": {"question": "Is the underlying distribution binomial?", "options": ["Yes", "No"]},
    "q26": {"question": "Is the data person-time type?", "options": ["Yes", "No"]},
    "q27": {"question": "Samples are independent?", "options": ["yes","no"]},
    #"q28": {"question": "Which Column segregates between the two samples (type exactly as in csv):", "options": [df.columns.tolist()]},
    "q29": {"question": "Is the data Categorical? ", "options": ["yes","no"]},
    "q30": {"question": "Is one variable Continuous and the other one Categorical? ", "options": ["yes","no"]},
    "q31": {"question": "Interested in predicting one variable from the other? ", "options": ["yes","no"]},
    "q32": {"question": "Are both Variables normal? ", "options": ["yes","no"]},
    "q33": {"question": "Are you assuming curve comes from a Weibull distribution: ", "options": ["yes","no"]},
    "q34": {"question": "Are you interested in comparison of survival curves of two groups with limited control of covariates:", "options": ["yes", "no"]},
    "q35": {"question": "Both Variables Continuous? ", "options": ["yes","no"]},
    "q36": {"question": "Do incidence rates remain constant over time: ", "options": ["yes","no"]},
    "q37": {"question": "Interested in relationship between 2 Variables? ", "options": ["yes","no"]},
    "q38": {"question": "Interested in trends over k binomial proportions? ", "options": ["yes","no"]},
    "q39": {"question": "2 x 2 Contingency Table? ", "options": ["yes","no"]},
    "q40": {"question": "2 x k Contingency Table? ", "options": ["yes","no"]},
    "q41": {"question": "RxC Contingency table, R>2 and C>2? ", "options": ["yes","no"]},
    "q100": {"question": "Outcome variable continous or binary? ", "options": ["continous","binary"]},
    "q101": {"question": "Time of events important? ", "options": ["yes","no"]},
    "q102": {"question": "Is this ordinal data? ", "options": ["yes","no"]},
    "q103": {"question": "Both Variables categorical? ", "options": ["yes","no"]},
    "q104": {"question": "Interested in test of association or reproducibility? ", "options": ["association","reproducibility"]},
    "q105": {"question": "Are all expected value greated than or equal to 5? ", "options": ["association","reproducibility"]},
    "q201": {"question": "Time of events not important? ", "options": ["yes","no"]}
}
